Webcounter CD - Attempt 7 - Debug IP address.

diff --git a/.github/workflows/on-every-release.yml b/.github/workflows/on-every-release.yml
--- a/.github/workflows/on-every-release.yml
+++ b/.github/workflows/on-every-release.yml
@@ -94,14 +94,15 @@ jobs:
   
             # Add the DNS address to GitHub Actions environment
             echo "EC2_IP=${EC2_IP}" >> $GITHUB_ENV
-
+  
             # Validate that DNS matches the expected pattern
-            if [[ ! "${EC2_IP}" =~ ^ec2-[0-9]+-[0-9]+-[0-9]+\.([a-z]{2}-[a-z]+-[0-9]+)\.compute\.amazonaws\.com$ ]]; then
-            echo "Failed to retrieve EC2 DNS. Destroying resources."
-            terraform destroy -auto-approve
-            exit 1
+            if [[ ! "${EC2_IP}" =~ ^ec2-[0-9]+-[0-9]+-[0-9]+\.([a-z]{2}-[a-z]+-\d{1,2})\.compute\.amazonaws\.com$ ]]; then
+              echo "Failed to retrieve EC2 DNS. Destroying resources."
+              terraform destroy -auto-approve
+              exit 1
             else
               echo "Extracted EC2 IP: ${EC2_IP}"
+              # Debugging output to identify the actual value
               echo "EC2_IP=${EC2_IP}" | cat -A
               echo "EC2_IP=${EC2_IP}" | od -c
               echo "EC2_IP=${EC2_IP}" | hexdump -C
