Webcounter CD - Attempt 7 - Debug IP address.

diff --git a/.github/workflows/on-every-release.yml b/.github/workflows/on-every-release.yml
--- a/.github/workflows/on-every-release.yml
+++ b/.github/workflows/on-every-release.yml
@@ -84,22 +84,24 @@ jobs:
             #TF_VAR_ec2_private_key: ${{ secrets.EC2_PRIVATE_KEY }}
           run: terraform apply -auto-approve
 
-        - name: Check Terraform IP Output
+        - name: Check Terraform DNS Output
           run: |
-            # Extract the IP address
-            EC2_IP=$(terraform output -raw ec2_public_ip | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1 | tr -d '[:space:][:cntrl:]')
+            # Extract the DNS address
+            EC2_IP=$(terraform output -raw ec2_public_dns)
             
-            # Debugging: Print the extracted IP address
-            echo "Extracted EC2 IP: ${EC2_IP}"
+            # Debugging: Print the extracted DNS address
+            echo "Extracted EC2 DNS: ${EC2_IP}"
             
-            # Add the IP address to GitHub Actions environment
+            # Add the DNS address to GitHub Actions environment
             echo "EC2_IP=${EC2_IP}" >> $GITHUB_ENV
-
-            # Validate the IP using regex
-            if [[ "${EC2_IP}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
-              echo "IP ADDRESS: ${EC2_IP}"
+        
+            # Validate that DNS is not empty
+            if [[ -z "${EC2_IP}" ]]; then
+              echo "Failed to retrieve EC2 DNS. Destroying resources."
+              terraform destroy -auto-approve
+              exit 1
             else
-              echo "Invalid IP address: ${EC2_IP}"
+              echo "Valid EC2 DNS: ${EC2_IP}"
               echo "Extracted EC2 IP: ${EC2_IP}"
               echo "EC2_IP=${EC2_IP}" | cat -A
               echo "EC2_IP=${EC2_IP}" | od -c
